### ISSUE TITLE
Wrong action urls in the invitation emails

### ISSUE THREAD

**Issue by asmaNode** [OpenPaaS-Suite/esn-frontend-calendar-public#20]
**Flow Chart of invite user (internal and external)** 

![Flow Chart(invite attendee) (1)](https://user-images.githubusercontent.com/43316837/97198481-2147c780-17af-11eb-9628-1b8ea5f1dc7f.jpg)

When an orgonizer create an event and invite a list of attendee , an email will be sent with the details of invitation and generate links  for each actions depending of type of the attendee
**External Attendee**
Links action will be generated with excal 
![action linksExcal](https://user-images.githubusercontent.com/43316837/97195874-18a1c200-17ac-11eb-8e4b-feb2120941fb.png)
Each action redirect to EXCAL app (calendar public SPA)

**Internal User**
Links action will be generated with calendar
![calendarLink](https://user-images.githubusercontent.com/43316837/97196224-851cc100-17ac-11eb-832a-d06192e3c46e.png)
Each action redirect to Calendar app with new state called participation (with event id)

When the application redirect to participation state  , the modal of detail event will be opened

**Comment by hantt12** [comment]
When I click on Yes option from the email, system opens a black page with a bunch of error logs in console. Is this something related ?

![Peek 2020-10-16 15-16](https://user-images.githubusercontent.com/53081477/96233739-afa79680-0fc2-11eb-8193-24e2826c5ef0.gif)

**Comment by asmaNode** [comment]
i thinks there is related pr did not merged , i will check this

**Comment by asmaNode** [comment]
@hantt12  : I just check the PR , this fix is for external users

**Comment by hantt12** [comment]
so I assume that this bug has not been fixed completely yet?

**Comment by huy-ta** [comment]
**Flow Chart of invite user (internal and external)** 

![Flow Chart(invite attendee) (1)](https://user-images.githubusercontent.com/43316837/97198481-2147c780-17af-11eb-9628-1b8ea5f1dc7f.jpg)

When an orgonizer create an event and invite a list of attendee , an email will be sent with the details of invitation and generate links  for each actions depending of type of the attendee
**External Attendee**
Links action will be generated with excal 
![action linksExcal](https://user-images.githubusercontent.com/43316837/97195874-18a1c200-17ac-11eb-8e4b-feb2120941fb.png)
Each action redirect to EXCAL app (calendar public SPA)

**Internal User**
Links action will be generated with calendar
![calendarLink](https://user-images.githubusercontent.com/43316837/97196224-851cc100-17ac-11eb-832a-d06192e3c46e.png)
Each action redirect to Calendar app with new state called participation (with event id)

When the application redirect to participation state  , the modal of detail event will be opened

**Comment by hantt12** [comment]
When user clicks on the options on event invitation email, system show Calendar with Undefined error

Expected: corrresponding event dialog should be shown with message: "You will attend this event"

![Peek 2020-11-20 10-31](https://user-images.githubusercontent.com/53081477/99754733-a5c20780-2b1b-11eb-92bd-af0bdffcd291.gif)
