### ISSUE TITLE
Adapt new version of esnI18nService.translate method to fix translation

### ISSUE THREAD

**Issue by tuanlc** [OpenPaaS-Suite/esn-frontend-calendar-public#7]
Topic: OpenPaaS-Suite/esn-frontend-common-libs#83

Reference PR: https://github.com/OpenPaaS-Suite/esn-frontend-inbox/pull/54

There is only one case need to be fixed: `"Participation updated: %s": "Participation updated: %s"`

**Comment by piavgh** [comment]
@tuanlc : There is no `esnI18nService.translate` inside this project.
I guess it's because all the translations are handled inside calendar module.

I will add tag `wontfix` and close this issue
